### ISSUE TITLE
Pipeline improvements

### ISSUE THREAD

**Issue by drychkov** [enriquea/feature-selection-r#1]
Hi Enrique,

First, thanks for the creating this feseR package! I found it very handy and I actually use it (with some modifications) in my research.

So, I made some improvements into the pipeline, like introducing parallel computations, AUC and Kohen's Kappa for benchmarking, and a tolerance parameter. Just wanted to let you know about them, maybe you would like to include these modifications into your official branch. Feel free to do so. You can check them out here: https://github.com/drychkov/feseR 

Thanks!
Dmitry

**Comment by ypriverol** [comment]
@drychkov can you create a PR into the main repo, we can review it and merge it.

**Comment by enriquea** [comment]
Hi @drychkov,

Thanks for using the package and your improvements are welcome. As suggested by @ypriverol, could you please make a PR?

Best,
Enrique

**Comment by drychkov** [comment]
Sure! Just created it.

**Comment by drychkov** [comment]
Guys, I think you need to fix Readme and description files. The changes I made there are not relevant to you (you need to keep ROCR package to import in the Description file though).

**Comment by enriquea** [comment]
All improvements are integrated. I've also fixed Readme, Description and the tests!
