### ISSUE TITLE
FeseR for mixed (categorical and numerical) data?

### ISSUE THREAD

**Issue by ravichas** [enriquea/feature-selection-r#5]
Hello FeseR team:

Will FeseR work (X2-MC-RFE-RF scheme) for a datset 
that includes both numerical and categorical data? 

Thanks

Ravi

**Comment by enriquea** [comment]
Hi @ravichas,

I haven't tried to run on mixed categorical/numerical data. You could 'force' your categorical to numerical and try this way, but I am not completely sure about the outcome.

Best,

E.
