### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by enriquea** [enriquea/feature-selection-r#8]
Hi @drychkov ,

Could you please to add some documentation to the input you did before?

Thanks in advance.

**Comment by drychkov** [comment]
Hey @enriquea 
Do you mean update the file combineFS.Rd? Or something else?

**Comment by enriquea** [comment]
Hi @drychkov 

Yes, I meant the combineFS doc (e.g. tolerance parameter). It would also be nice to add some description for this internal helper function: https://github.com/enriquea/feseR/blob/248642c25dede22aac9903dad021f5dc8ce94649/R/fs_functions.R#L471 and others you have added before.

Thanks in advance!
